/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cadastro_Tradutor_Traducoes;

import java.io.File;
import java.text.MessageFormat;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Willian Nunes Maciel
 */
public class TelaTraducoes extends javax.swing.JFrame {

    /**
     * Creates new form TelaTraducoes
     */
    public TelaTraducoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTraducoes = new javax.swing.JTable();
        jLabelTituloTradudores = new javax.swing.JLabel();
        jLabelCompetencias = new javax.swing.JLabel();
        jComboBoxCompetencias = new javax.swing.JComboBox<>();
        jLabelIdiomaOrigem = new javax.swing.JLabel();
        jComboBoxIdiomaOrigem = new javax.swing.JComboBox<>();
        jLabelIdiomaDestino = new javax.swing.JLabel();
        jComboBoxIdiomaDestino = new javax.swing.JComboBox<>();
        jLabelIdiomaOriginal = new javax.swing.JLabel();
        jComboBoxIdiomaOriginal = new javax.swing.JComboBox<>();
        jLabelNacionalidade = new javax.swing.JLabel();
        jComboBoxNacionalidade = new javax.swing.JComboBox<>();
        jLabelServicosEspecializados = new javax.swing.JLabel();
        jComboBoxServicosEspecializados = new javax.swing.JComboBox<>();
        jLabelObservacoes = new javax.swing.JLabel();
        textAreaObservacoes = new java.awt.TextArea();
        jButtonAnexarArquivo = new javax.swing.JButton();
        jTextFieldAnexarArquivo = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonVoltarTelaPrincipal = new javax.swing.JButton();
        jButtonImprimir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabelFundoTraducoes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Traduções");
        setResizable(false);
        getContentPane().setLayout(null);

        jTableTraducoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Competências", "Idioma(Origem)", "Idioma(Destino)", "Idioma Original", "Nacionalidade", "Serv. Especializados", "Observações"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTraducoes.setGridColor(new java.awt.Color(255, 255, 255));
        jTableTraducoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableTraducoesKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTableTraducoes);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 420, 810, 190);

        jLabelTituloTradudores.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabelTituloTradudores.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloTradudores.setText("Cadastro de Traduções");
        getContentPane().add(jLabelTituloTradudores);
        jLabelTituloTradudores.setBounds(120, 10, 360, 50);

        jLabelCompetencias.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelCompetencias.setText("Competências:");
        getContentPane().add(jLabelCompetencias);
        jLabelCompetencias.setBounds(30, 70, 130, 30);

        jComboBoxCompetencias.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxCompetencias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Área Financeira", "Automotivo", "Aviação", "Contabilidade", "Engenharia", "Física", "Gastronomia", "Jurídico", "Literatura", "Medicina", "Tecnologia", "Turismo" }));
        getContentPane().add(jComboBoxCompetencias);
        jComboBoxCompetencias.setBounds(150, 70, 230, 30);

        jLabelIdiomaOrigem.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelIdiomaOrigem.setText("Idioma (Origem):");
        getContentPane().add(jLabelIdiomaOrigem);
        jLabelIdiomaOrigem.setBounds(30, 110, 140, 30);

        jComboBoxIdiomaOrigem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxIdiomaOrigem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Alemão", "Chinês Mandarim", "Coreano", "Espanhol", "Francês", "Grego", "Holandês", "Inglês", "Italiano", "Japonês", "Polonês", "Português", "Russo", "Tailandês" }));
        getContentPane().add(jComboBoxIdiomaOrigem);
        jComboBoxIdiomaOrigem.setBounds(150, 110, 230, 30);

        jLabelIdiomaDestino.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelIdiomaDestino.setText("Idioma (Destino):");
        getContentPane().add(jLabelIdiomaDestino);
        jLabelIdiomaDestino.setBounds(30, 150, 150, 30);

        jComboBoxIdiomaDestino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxIdiomaDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Alemão", "Chinês Mandarim", "Coreano", "Espanhol", "Francês", "Grego", "Holandês", "Inglês", "Italiano", "Japonês", "Polonês", "Português", "Russo", "Tailandês" }));
        getContentPane().add(jComboBoxIdiomaDestino);
        jComboBoxIdiomaDestino.setBounds(150, 151, 230, 30);

        jLabelIdiomaOriginal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelIdiomaOriginal.setText("Idioma Original:");
        getContentPane().add(jLabelIdiomaOriginal);
        jLabelIdiomaOriginal.setBounds(30, 190, 120, 30);

        jComboBoxIdiomaOriginal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxIdiomaOriginal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Alemão", "Chinês Mandarim", "Coreano", "Espanhol", "Francês", "Grego", "Holandês", "Inglês", "Italiano", "Japonês", "Polonês", "Português", "Russo", "Tailandês" }));
        getContentPane().add(jComboBoxIdiomaOriginal);
        jComboBoxIdiomaOriginal.setBounds(150, 190, 230, 30);

        jLabelNacionalidade.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelNacionalidade.setText("Nacionalidade:");
        getContentPane().add(jLabelNacionalidade);
        jLabelNacionalidade.setBounds(30, 230, 110, 30);

        jComboBoxNacionalidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxNacionalidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Afeganistão ", "Argentina ", "Austrália", "Bahamas", "Brasil", "Bulgária", "Chile", "China", "Cuba", "Espanha", "Estados Unidos", "França", "Grécia", "Holanda", "Japão", "Polônia", "Russia", "Tailândia" }));
        getContentPane().add(jComboBoxNacionalidade);
        jComboBoxNacionalidade.setBounds(150, 231, 230, 30);

        jLabelServicosEspecializados.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelServicosEspecializados.setText("Serviços Especializados:");
        getContentPane().add(jLabelServicosEspecializados);
        jLabelServicosEspecializados.setBounds(30, 270, 170, 30);

        jComboBoxServicosEspecializados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxServicosEspecializados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Closed Caption", "Diagramação", "Edição de vídeo", "Inserir Legenda", "Interpretação Simultânea", "Linguagem de Sinais", "Revisão", "Tradução" }));
        getContentPane().add(jComboBoxServicosEspecializados);
        jComboBoxServicosEspecializados.setBounds(200, 271, 180, 30);

        jLabelObservacoes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelObservacoes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelObservacoes.setText("Observações Gerais:");
        getContentPane().add(jLabelObservacoes);
        jLabelObservacoes.setBounds(490, 90, 160, 20);
        getContentPane().add(textAreaObservacoes);
        textAreaObservacoes.setBounds(490, 120, 300, 180);

        jButtonAnexarArquivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAnexarArquivo.setText("Anexar Arquivo");
        jButtonAnexarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnexarArquivoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAnexarArquivo);
        jButtonAnexarArquivo.setBounds(30, 320, 170, 30);
        getContentPane().add(jTextFieldAnexarArquivo);
        jTextFieldAnexarArquivo.setBounds(210, 320, 250, 30);

        jButtonCadastrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrar);
        jButtonCadastrar.setBounds(20, 380, 110, 30);

        jButtonLimpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonLimpar.setText("Limpar Dados");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpar);
        jButtonLimpar.setBounds(140, 380, 120, 30);

        jButtonVoltarTelaPrincipal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonVoltarTelaPrincipal.setText("Voltar");
        jButtonVoltarTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarTelaPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltarTelaPrincipal);
        jButtonVoltarTelaPrincipal.setBounds(500, 380, 120, 30);

        jButtonImprimir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonImprimir.setText("Imprimir");
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonImprimir);
        jButtonImprimir.setBounds(640, 380, 120, 30);

        jButtonAlterar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlterar);
        jButtonAlterar.setBounds(280, 380, 90, 30);

        jButtonExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(390, 380, 90, 30);

        jLabelFundoTraducoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/traducoesfundo.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoTraducoes);
        jLabelFundoTraducoes.setBounds(0, -610, 1850, 1270);
        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 270, 2, 2);

        setSize(new java.awt.Dimension(817, 648));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:
        
        jComboBoxCompetencias.setSelectedIndex(0);
        jComboBoxIdiomaOrigem.setSelectedIndex(0);
        jComboBoxIdiomaDestino.setSelectedIndex(0);
        jComboBoxIdiomaOriginal.setSelectedIndex(0);
        jComboBoxNacionalidade.setSelectedIndex(0);
        jComboBoxServicosEspecializados.setSelectedIndex(0);
        textAreaObservacoes.setText(" ");
        jTextFieldAnexarArquivo.setText("");
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonAnexarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnexarArquivoActionPerformed
        // TODO add your handling code here:
        
        JFileChooser jf = new JFileChooser();
        jf.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jf.showOpenDialog(this);
        File f = jf.getSelectedFile();
        jTextFieldAnexarArquivo.setText(f.getPath());
    }//GEN-LAST:event_jButtonAnexarArquivoActionPerformed

    private void jButtonVoltarTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarTelaPrincipalActionPerformed
        // TODO add your handling code here:
        
        new TelaPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarTelaPrincipalActionPerformed

    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
       
    MessageFormat header = new MessageFormat("Cadastros Realizados de Traduções");
    MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        
        try{
           
            jTableTraducoes.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        }catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
                
        }
    }//GEN-LAST:event_jButtonImprimirActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        // TODO add your handling code here:
       String Competencias = jComboBoxCompetencias.getSelectedItem().toString().trim();
       String Idioma_origem = jComboBoxIdiomaOrigem.getSelectedItem().toString().trim();
       String idioma_destino = jComboBoxIdiomaDestino.getSelectedItem().toString().trim();
       String idioma_original = jComboBoxIdiomaOriginal.getSelectedItem().toString().trim();
       String nacionalidade = jComboBoxNacionalidade.getSelectedItem().toString().trim();
       String servicos_especializado = jComboBoxServicosEspecializados.getSelectedItem().toString().trim();
       String observacoes = textAreaObservacoes.getText().trim();
       String anexar_arquivo = jTextFieldAnexarArquivo.getText().trim();
       
       
       DefaultTableModel val = (DefaultTableModel) jTableTraducoes.getModel();
               
       val.addRow(new String[]{Competencias, Idioma_origem, idioma_destino, idioma_original, nacionalidade,servicos_especializado,observacoes,anexar_arquivo});
       
       jComboBoxCompetencias.setSelectedItem("");
       jComboBoxIdiomaOrigem.setSelectedItem("");
       jComboBoxIdiomaDestino.setSelectedItem("");
       jComboBoxIdiomaOriginal.setSelectedItem("");
       jComboBoxNacionalidade.setSelectedItem("");
       jComboBoxServicosEspecializados.setSelectedItem("");
       textAreaObservacoes.setText("");
       jTextFieldAnexarArquivo.setText("");
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
       
        if(jTableTraducoes.getSelectedRow()!= -1){
           
       DefaultTableModel val = (DefaultTableModel) jTableTraducoes.getModel();
        val.removeRow(jTableTraducoes.getSelectedRow());    
    }else{
            JOptionPane.showMessageDialog(null, "Selecione um item para excluir!");
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableTraducoesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableTraducoesKeyReleased
  
        jTableTraducoes.setValueAt(jComboBoxCompetencias.getSelectedItem(), jTableTraducoes.getSelectedRow(), 0);
        jTableTraducoes.setValueAt(jComboBoxIdiomaOrigem.getSelectedItem(), jTableTraducoes.getSelectedRow(), 1);
        jTableTraducoes.setValueAt(jComboBoxIdiomaDestino.getSelectedItem(), jTableTraducoes.getSelectedRow(), 2);
        jTableTraducoes.setValueAt(jComboBoxIdiomaOriginal.getSelectedItem(), jTableTraducoes.getSelectedRow(), 3);
        jTableTraducoes.setValueAt(jComboBoxNacionalidade.getSelectedItem(), jTableTraducoes.getSelectedRow(),4);
        jTableTraducoes.setValueAt(jComboBoxServicosEspecializados.getSelectedItem(), jTableTraducoes.getSelectedRow(), 5);
        jTableTraducoes.setValueAt(textAreaObservacoes.getText(), jTableTraducoes.getSelectedRow(), 6);        
    
    }//GEN-LAST:event_jTableTraducoesKeyReleased

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:
        jButtonAlterar alterar = new jButtonAlterar();
              
        if(jTableTraducoes.getSelectedRow() != -1 ){

        jTableTraducoes.setValueAt(jComboBoxCompetencias.getSelectedItem(), jTableTraducoes.getSelectedRow(), 0);
        jTableTraducoes.setValueAt(jComboBoxIdiomaOrigem.getSelectedItem(), jTableTraducoes.getSelectedRow(), 1);
        jTableTraducoes.setValueAt(jComboBoxIdiomaDestino.getSelectedItem(), jTableTraducoes.getSelectedRow(), 2);
        jTableTraducoes.setValueAt(jComboBoxIdiomaOriginal.getSelectedItem(), jTableTraducoes.getSelectedRow(), 3);
        jTableTraducoes.setValueAt(jComboBoxNacionalidade.getSelectedItem(), jTableTraducoes.getSelectedRow(),4);
        jTableTraducoes.setValueAt(jComboBoxServicosEspecializados.getSelectedItem(), jTableTraducoes.getSelectedRow(), 5);
        jTableTraducoes.setValueAt(textAreaObservacoes.getText(), jTableTraducoes.getSelectedRow(), 6);        
        
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTraducoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaTraducoes().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonAnexarArquivo;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonVoltarTelaPrincipal;
    private javax.swing.JComboBox<String> jComboBoxCompetencias;
    private javax.swing.JComboBox<String> jComboBoxIdiomaDestino;
    private javax.swing.JComboBox<String> jComboBoxIdiomaOrigem;
    private javax.swing.JComboBox<String> jComboBoxIdiomaOriginal;
    private javax.swing.JComboBox<String> jComboBoxNacionalidade;
    private javax.swing.JComboBox<String> jComboBoxServicosEspecializados;
    private javax.swing.JLabel jLabelCompetencias;
    private javax.swing.JLabel jLabelFundoTraducoes;
    private javax.swing.JLabel jLabelIdiomaDestino;
    private javax.swing.JLabel jLabelIdiomaOrigem;
    private javax.swing.JLabel jLabelIdiomaOriginal;
    private javax.swing.JLabel jLabelNacionalidade;
    private javax.swing.JLabel jLabelObservacoes;
    private javax.swing.JLabel jLabelServicosEspecializados;
    private javax.swing.JLabel jLabelTituloTradudores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableTraducoes;
    private javax.swing.JTextField jTextFieldAnexarArquivo;
    private java.awt.TextArea textAreaObservacoes;
    // End of variables declaration//GEN-END:variables

    private static class jButtonAlterar {

        public jButtonAlterar() {
        }
    }
}
