/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cadastro_Tradutor_Traducoes;

import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Willian Nunes Maciel
 */
public class TelaTradutores extends javax.swing.JFrame {

    /**
     * Creates new form TelaTradutores
     */
    public TelaTradutores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTituloTradutores = new javax.swing.JLabel();
        jLabelNomeTradutor = new javax.swing.JLabel();
        jTextFieldNomeTradutor = new javax.swing.JTextField();
        jLabelNacionalidade = new javax.swing.JLabel();
        jTextFieldNacionalidade = new javax.swing.JTextField();
        jLabelCpf = new javax.swing.JLabel();
        jTextFieldCpf = new javax.swing.JTextField();
        jLabelIdade = new javax.swing.JLabel();
        jTextFieldIdade = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelGenero = new javax.swing.JLabel();
        jComboBoxGenero = new javax.swing.JComboBox<>();
        jLabelListaTradutores = new javax.swing.JLabel();
        jButtonIncluir = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonLimparCampos = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jButtonImprimirTradutores = new javax.swing.JButton();
        jScrollPaneTabTradutores = new javax.swing.JScrollPane();
        jTableTradutores = new javax.swing.JTable();
        textAreaFormacao = new java.awt.TextArea();
        jLabelFormacaoEspecializacao = new javax.swing.JLabel();
        jLabelImgFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Tradutores");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelTituloTradutores.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabelTituloTradutores.setText("Cadastro de Tradutores");
        getContentPane().add(jLabelTituloTradutores);
        jLabelTituloTradutores.setBounds(250, 0, 360, 40);

        jLabelNomeTradutor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNomeTradutor.setText("Nome do Tradutor:");
        getContentPane().add(jLabelNomeTradutor);
        jLabelNomeTradutor.setBounds(20, 50, 130, 14);

        jTextFieldNomeTradutor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldNomeTradutor);
        jTextFieldNomeTradutor.setBounds(160, 80, 230, 30);

        jLabelNacionalidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNacionalidade.setText("Nacionalidade:");
        getContentPane().add(jLabelNacionalidade);
        jLabelNacionalidade.setBounds(20, 190, 130, 20);

        jTextFieldNacionalidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldNacionalidade);
        jTextFieldNacionalidade.setBounds(160, 190, 230, 30);

        jLabelCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCpf.setText("CPF:");
        getContentPane().add(jLabelCpf);
        jLabelCpf.setBounds(20, 160, 130, 14);

        jTextFieldCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldCpf);
        jTextFieldCpf.setBounds(160, 153, 230, 30);

        jLabelIdade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelIdade.setText("Idade:");
        getContentPane().add(jLabelIdade);
        jLabelIdade.setBounds(20, 130, 130, 14);

        jTextFieldIdade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldIdade);
        jTextFieldIdade.setBounds(160, 120, 230, 30);

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEmail.setText("E-mail:");
        getContentPane().add(jLabelEmail);
        jLabelEmail.setBounds(20, 90, 130, 14);

        jTextFieldEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldEmail);
        jTextFieldEmail.setBounds(160, 43, 230, 30);

        jLabelGenero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelGenero.setText("Gênero:");
        getContentPane().add(jLabelGenero);
        jLabelGenero.setBounds(20, 230, 130, 20);

        jComboBoxGenero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Masculino", "Feminino" }));
        getContentPane().add(jComboBoxGenero);
        jComboBoxGenero.setBounds(160, 230, 230, 23);

        jLabelListaTradutores.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jLabelListaTradutores.setText("Lista de Tradutores Cadastrados");
        getContentPane().add(jLabelListaTradutores);
        jLabelListaTradutores.setBounds(250, 260, 240, 16);

        jButtonIncluir.setText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIncluir);
        jButtonIncluir.setBounds(100, 280, 61, 23);

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(180, 280, 80, 23);

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlterar);
        jButtonAlterar.setBounds(290, 280, 65, 23);

        jButtonLimparCampos.setText("Limpar Campos");
        jButtonLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparCamposActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimparCampos);
        jButtonLimparCampos.setBounds(380, 280, 130, 23);

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar);
        jButtonVoltar.setBounds(530, 280, 61, 23);

        jButtonImprimirTradutores.setText("Imprimir");
        jButtonImprimirTradutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirTradutoresActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonImprimirTradutores);
        jButtonImprimirTradutores.setBounds(610, 280, 100, 23);

        jTableTradutores.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableTradutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "E-mail", "Idade", "CPF", "Nacionalidade", "Gênero", "Form. e Espec."
            }
        ));
        jTableTradutores.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPaneTabTradutores.setViewportView(jTableTradutores);

        getContentPane().add(jScrollPaneTabTradutores);
        jScrollPaneTabTradutores.setBounds(10, 310, 810, 140);
        getContentPane().add(textAreaFormacao);
        textAreaFormacao.setBounds(570, 100, 230, 160);

        jLabelFormacaoEspecializacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelFormacaoEspecializacao.setText("Formações e Especializações do Tradutor");
        getContentPane().add(jLabelFormacaoEspecializacao);
        jLabelFormacaoEspecializacao.setBounds(560, 80, 250, 15);

        jLabelImgFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Global Team.png"))); // NOI18N
        getContentPane().add(jLabelImgFundo);
        jLabelImgFundo.setBounds(-110, 0, 1080, 550);

        setSize(new java.awt.Dimension(847, 485));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:
        if(jTableTradutores.getSelectedRow() != -1 ){

        jTableTradutores.setValueAt(jTextFieldNomeTradutor.getText(), jTableTradutores.getSelectedRow(), 0);
        jTableTradutores.setValueAt(jTextFieldEmail.getText(), jTableTradutores.getSelectedRow(), 1);
        jTableTradutores.setValueAt(jTextFieldIdade.getText(), jTableTradutores.getSelectedRow(), 2);
        jTableTradutores.setValueAt(jTextFieldCpf.getText(), jTableTradutores.getSelectedRow(), 3);
        jTableTradutores.setValueAt(jTextFieldNacionalidade.getText(), jTableTradutores.getSelectedRow(),4);
        jTableTradutores.setValueAt(jComboBoxGenero.getSelectedItem(), jTableTradutores.getSelectedRow(), 5);
        jTableTradutores.setValueAt(textAreaFormacao.getText(), jTableTradutores.getSelectedRow(), 6);        
        
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
            // TODO add your handling code here:
       String nome = jTextFieldNomeTradutor.getText().trim();
       String mail = jTextFieldEmail.getText().trim();
       String idade = jTextFieldIdade.getText().trim();
       String cpf = jTextFieldCpf.getText().trim();
       String nacionalidade = jTextFieldNacionalidade.getText().trim();
       String sexo = jComboBoxGenero.getSelectedItem().toString().trim();
       String formacao = textAreaFormacao.getText().trim();
       
       DefaultTableModel val = (DefaultTableModel) jTableTradutores.getModel();
               
       val.addRow(new String[]{nome, mail, idade, cpf, nacionalidade,sexo,formacao});
       
       jTextFieldNomeTradutor.setText("");
       jTextFieldEmail.setText("");
       jTextFieldIdade.setText("");
       jTextFieldCpf.setText("");
       jTextFieldNacionalidade.setText("");
       jComboBoxGenero.setSelectedItem("");
       textAreaFormacao.setText("");
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        
        new TelaPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonImprimirTradutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirTradutoresActionPerformed

            MessageFormat header = new MessageFormat("Cadastros Realizados de Tradutores");
            MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        
        try{
           
            jTableTradutores.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        }catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
                
        }   
    }//GEN-LAST:event_jButtonImprimirTradutoresActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        
        if(jTableTradutores.getSelectedRow()!= -1){
           
       DefaultTableModel val = (DefaultTableModel) jTableTradutores.getModel();
        val.removeRow(jTableTradutores.getSelectedRow());    
    }else{
            JOptionPane.showMessageDialog(null, "Selecione um item para excluir!");
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparCamposActionPerformed

    jTextFieldNomeTradutor.setText("");
    jTextFieldEmail.setText("");
    jTextFieldIdade.setText("");
    jTextFieldCpf.setText("");
    jTextFieldNacionalidade.setText("");
    jComboBoxGenero.setSelectedIndex(-1);
    textAreaFormacao.setText(" ");
    }//GEN-LAST:event_jButtonLimparCamposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTradutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaTradutores().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonImprimirTradutores;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonLimparCampos;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxGenero;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFormacaoEspecializacao;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelIdade;
    private javax.swing.JLabel jLabelImgFundo;
    private javax.swing.JLabel jLabelListaTradutores;
    private javax.swing.JLabel jLabelNacionalidade;
    private javax.swing.JLabel jLabelNomeTradutor;
    private javax.swing.JLabel jLabelTituloTradutores;
    private javax.swing.JScrollPane jScrollPaneTabTradutores;
    private javax.swing.JTable jTableTradutores;
    private javax.swing.JTextField jTextFieldCpf;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIdade;
    private javax.swing.JTextField jTextFieldNacionalidade;
    private javax.swing.JTextField jTextFieldNomeTradutor;
    private java.awt.TextArea textAreaFormacao;
    // End of variables declaration//GEN-END:variables
}
