/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cadastro_Tradutor_Traducoes;

import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Willian Nunes Maciel
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @param login
     * @param senha
     * @return 
     */
    
     public boolean checkLogin (String login, String senha){
     return login.equals("teste") && senha.equals("1234");
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButtonLimparDados = new javax.swing.JButton();
        jButtonEntrar = new javax.swing.JButton();
        jLabelsSenha = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelTitulo2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelImgFundo = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Tradutor e Traduções");
        setResizable(false);
        getContentPane().setLayout(null);

        jButtonLimparDados.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jButtonLimparDados.setText("Limpar Dados");
        jButtonLimparDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparDadosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimparDados);
        jButtonLimparDados.setBounds(260, 240, 140, 29);

        jButtonEntrar.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEntrar);
        jButtonEntrar.setBounds(130, 240, 90, 29);

        jLabelsSenha.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabelsSenha.setText("Senha:");
        getContentPane().add(jLabelsSenha);
        jLabelsSenha.setBounds(80, 180, 100, 30);

        jLabelUsuario.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabelUsuario.setText("Usuário:");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(80, 130, 110, 30);

        jTextFieldUsuario.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsuario);
        jTextFieldUsuario.setBounds(160, 130, 200, 30);

        jPasswordFieldSenha.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jPasswordFieldSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(160, 180, 200, 30);

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTitulo.setText("Cadastro de Tradutor e Traduções");
        getContentPane().add(jLabelTitulo);
        jLabelTitulo.setBounds(140, 0, 410, 50);

        jLabelTitulo2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelTitulo2.setText("Acesso Restrito");
        getContentPane().add(jLabelTitulo2);
        jLabelTitulo2.setBounds(260, 50, 140, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/loginBoneco.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 60, 200, 260);

        jLabelImgFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/imagem login 3.jpg"))); // NOI18N
        jLabelImgFundo.setText("jLabel1");
        getContentPane().add(jLabelImgFundo);
        jLabelImgFundo.setBounds(-10, -10, 620, 390);

        setSize(new java.awt.Dimension(595, 392));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        // TODO add your handling code here:
        if(this.checkLogin(jTextFieldUsuario.getText(), new String(jPasswordFieldSenha.getPassword()))){
            new TelaPrincipal().setVisible(true);
            JOptionPane.showMessageDialog(null, "Seja Bem-Vindo!");
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Usuário ou Senha Inválidos!");
        }
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    private void jButtonLimparDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparDadosActionPerformed
        // TODO add your handling code here:
        this.jTextFieldUsuario.setText("");
        this.jPasswordFieldSenha.setText("");
    }//GEN-LAST:event_jButtonLimparDadosActionPerformed

    private void jPasswordFieldSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        
            if(this.checkLogin(jTextFieldUsuario.getText(), new String(jPasswordFieldSenha.getPassword()))){
            new TelaPrincipal().setVisible(true);
            JOptionPane.showMessageDialog(null, "Seja Bem-Vindo!");
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Usuário ou Senha Inválidos!");
        }
        
    }
        
    }//GEN-LAST:event_jPasswordFieldSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonLimparDados;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelImgFundo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelsSenha;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldUsuario;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
